[window]
	opacity  = 0.65

[terminal.shell]
  program = "/usr/bin/fish"

[font]
  #normal = { family = "0xProto Nerd Font Mono", style = "Regular" } maybe someday change?
  normal = { family = "Hack Nerd Font Mono", style = "Regular" }
  bold = { family = "Hack Nerd Font Mono", style = "Bold" }
  italic = { family = "Hack Nerd Font Mono", style = "Italic" }
  bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }

[scrolling]
  history = 20000

[colors.primary]
	background = '#000000'
	foreground = '#FFFFFF' 
[colors.normal]
	black = '#1a1a1a'
	red = '#f4005f'
	green = '#98e024'
	yellow = '#fa8419'
	blue = '#9d65ff'
	magenta = '#f4005f'
	cyan = '#58d1eb'
	white = '#c4c5b5'
[colors.bright]
	black = '#625e4c'
	red = '#f4005f'
	green = '#98e024'
	yellow = '#e0d561'
	blue = '#9d65ff'
	magenta = '#f4005f'
	cyan = '#58d1eb'
	white = '#f6f6ef'
